BEGIN;

DROP TABLE IF EXISTS questionnaires_screeningtoolquestionresponse;
DROP TABLE IF EXISTS questionnaires_screeningtoolresponse;
DROP TABLE IF EXISTS questionnaires_questioninputchoice;
DROP TABLE IF EXISTS questionnaires_question;
DROP TABLE IF EXISTS questionnaires_screeningtool;
DROP TABLE IF EXISTS questionnaires_questionnaire;

-- Indexes
DROP INDEX IF EXISTS questionnaires_questionnaire_name;
DROP INDEX IF EXISTS questionnaires_screeningtool_questionnaire_id;
DROP INDEX IF EXISTS questionnaires_screeningtool_genders;
DROP INDEX IF EXISTS questionnaires_screeningtool_client_types;
DROP INDEX IF EXISTS questionnaires_screeningtool_min_age;
DROP INDEX IF EXISTS questionnaires_screeningtool_max_age;
DROP INDEX IF EXISTS questionnaires_question_questionnaire_id;
DROP INDEX IF EXISTS questionnaires_questioninputchoice_question_id;
DROP INDEX IF EXISTS questionnaires_questioninputchoice_choice;
DROP INDEX IF EXISTS questionnaires_screeningtoolresponse_screeningtool_id;
DROP INDEX IF EXISTS questionnaires_screeningtoolresponse_facility_id;
DROP INDEX IF EXISTS questionnaires_screeningtoolresponse_client_id;
DROP INDEX IF EXISTS questionnaires_screeningtoolquestionresponse_screeningtoolresponse_id;
DROP INDEX IF EXISTS questionnaires_screeningtoolquestionresponse_question_id;
DROP INDEX IF EXISTS questionnaires_screeningtoolquestionresponse_response;

COMMIT;
