# Options for analysis running.
run:
  timeout: 3m
  skip-dirs:
    - pkg/mycarehub/presentation/graph/
    - ./tests/

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - asciicheck
    - dogsled
    - goheader
    - gosec
    - misspell
    - rowserrcheck
    - sqlclosecheck

linters-settings:
  staticcheck:
    checks: ["all"]
  funlen:
    lines: -1 
    statements: -1
  gosec:
    excludes:
      - G601
      - G304
      - G101