package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/savannahghi/mycarehub/pkg/mycarehub/application/dto"
	"github.com/savannahghi/mycarehub/pkg/mycarehub/domain"
)

// CreateCommunity is the resolver for the createCommunity field.
func (r *mutationResolver) CreateCommunity(ctx context.Context, input *dto.CommunityInput) (*domain.Community, error) {
	r.checkPreconditions()

	return r.mycarehub.Community.CreateCommunity(ctx, input)
}
