package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/savannahghi/mycarehub/pkg/mycarehub/application/dto"
	"github.com/savannahghi/mycarehub/pkg/mycarehub/domain"
)

// CreateOauthClient is the resolver for the createOauthClient field.
func (r *mutationResolver) CreateOauthClient(ctx context.Context, input dto.OauthClientInput) (*domain.OauthClient, error) {
	return r.mycarehub.Oauth.CreateOauthClient(ctx, input)
}

// ListOauthClients is the resolver for the listOauthClients field.
func (r *queryResolver) ListOauthClients(ctx context.Context) ([]*domain.OauthClient, error) {
	panic(fmt.Errorf("not implemented: ListOauthClients - listOauthClients"))
}
