package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"

	"github.com/savannahghi/feedlib"
	"github.com/savannahghi/mycarehub/pkg/mycarehub/domain"
)

// SendOtp is the resolver for the sendOTP field.
func (r *queryResolver) SendOtp(ctx context.Context, username string, flavour feedlib.Flavour) (*domain.OTPResponse, error) {
	r.checkPreconditions()
	return r.mycarehub.OTP.GenerateAndSendOTP(ctx, username, flavour)
}
