package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"context"

	"github.com/savannahghi/feedlib"
)

// SendOtp is the resolver for the sendOTP field.
func (r *queryResolver) SendOtp(ctx context.Context, phoneNumber string, flavour feedlib.Flavour) (string, error) {
	r.checkPreconditions()
	return r.mycarehub.OTP.GenerateAndSendOTP(ctx, phoneNumber, flavour)
}
