package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/savannahghi/mycarehub/pkg/mycarehub/domain"
	"github.com/savannahghi/mycarehub/pkg/mycarehub/presentation/graph/generated"
)

// VerificationCodeStatus is the resolver for the verificationCodeStatus field.
func (r *bookingResolver) VerificationCodeStatus(ctx context.Context, obj *domain.Booking) (string, error) {
	panic(fmt.Errorf("not implemented: VerificationCodeStatus - verificationCodeStatus"))
}

// Booking returns generated.BookingResolver implementation.
func (r *Resolver) Booking() generated.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
