package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/savannahghi/mycarehub/pkg/mycarehub/domain"
	"github.com/savannahghi/mycarehub/pkg/mycarehub/presentation/graph/generated"
)

// Type is the resolver for the type field.
func (r *identifierResolver) Type(ctx context.Context, obj *domain.Identifier) (string, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Identifier returns generated.IdentifierResolver implementation.
func (r *Resolver) Identifier() generated.IdentifierResolver { return &identifierResolver{r} }

type identifierResolver struct{ *Resolver }
