apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: db-svc-mycarehub
spec:
  selector:
    app: {{ .Release.Name }}
    component: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
